import type { EffectDefinition } from './react-bits-catalog';

export const firstEffects: EffectDefinition[] = [
    {
        kind: 'gradientWaves',
        title: 'Gradient Waves',
        description: 'Rolling luminous waves',
        defaults: {
            horizonColor: '#5227ff',
            waveColor: '#ff9ffc',
            crestColor: '#ffffff',
            speed: 0.4,
            amplitude: 2.5,
            waveScale: 0.6,
            waveRatio: 0.9,
            swell: 35,
            turbulence: 20,
            tilt: 1.11,
            zoom: 1,
            height: 5.5,
            fogDepth: 15,
            detail: 'medium',
            brightness: 1,
            opacity: 1,
            mouseInteraction: true,
            parallaxStrength: 0.5,
            grain: true,
            grainIntensity: 0.05,
        },
        choices: { detail: ['low', 'medium', 'high'] },
    },
    {
        kind: 'webThreads',
        title: 'Web Threads',
        description: 'Glowing interwoven lines',
        defaults: {
            color1: '#5227ff',
            color2: '#ff9ffc',
            color3: '#ffffff',
            backgroundColor: '#0d1012',
            speed: 0.2,
            threadCount: 6,
            frequency: 5,
            spread: 0.18,
            taper: 1,
            position: 0.5,
            fanMode: 'center',
            glow: 0.02,
            falloff: 0.6,
            thickness: 1.1,
            brightness: 0.6,
            opacity: 1,
            mirror: true,
            shimmer: false,
            grain: true,
            grainIntensity: 0.05,
            mouseInteraction: true,
            mouseStrength: 0.3,
        },
        choices: { fanMode: ['center', 'left', 'right'] },
    },
    {
        kind: 'lightTunnel',
        title: 'Light Tunnel',
        description: 'Pulsing cables in depth',
        defaults: {
            cableColor: '#a855f7',
            pulseColor: '#a855f7',
            tunnelColor: '#5227ff',
            tunnelOpacity: 0,
            speed: 0.1,
            flowDirection: 'outward',
            pulseSpeed: 2,
            pulseLength: 0.28,
            pulseBlend: 1,
            pulseWidth: 1,
            cableCount: 20,
            thickness: 0.35,
            rimWidth: 0.15,
            waviness: 0.3,
            sway: 0.5,
            size: 1,
            centerX: 0,
            centerY: 0,
            glow: 1,
            fadeNear: 0.5,
            fadeFar: 2,
            brightness: 1,
            colorVariance: true,
            grain: true,
            grainIntensity: 0.05,
            opacity: 1,
            mouseInteraction: true,
            mouseStrength: 0.1,
        },
        choices: { flowDirection: ['outward', 'inward'] },
    },
    {
        kind: 'scanner',
        title: 'Scanner',
        description: 'Moving scan field',
        defaults: {
            color1: '#5227ff',
            color2: '#ff9ffc',
            color3: '#ffffff',
            speed: 0.5,
            sweepSpeed: 0.25,
            sweepWidth: 1.6,
            sweepFalloff: 6,
            scale: 1.5,
            frequency: 2,
            ripple: 0.22,
            bandDensity: 11,
            lineSharpness: 5.5,
            glow: 0.22,
            scanDirection: 'vertical',
            colorSpread: 0.7,
            brightness: 1,
            contrast: 1.15,
            softness: 1.4,
            vignette: 0.45,
            scanline: true,
            grain: true,
            grainIntensity: 0.05,
            opacity: 1,
            mouseInteraction: true,
            mouseRadius: 0.5,
            mouseStrength: 0.5,
        },
        choices: { scanDirection: ['vertical', 'horizontal', 'diagonal'] },
    },
    {
        kind: 'lightfall',
        title: 'Lightfall',
        description: 'Descending color streaks',
        defaults: {
            colors: ['#a6c8ff', '#5227ff', '#ff9ffc'],
            backgroundColor: '#0a29ff',
            speed: 0.5,
            streakCount: 2,
            streakWidth: 1,
            streakLength: 1,
            glow: 1,
            density: 0.6,
            twinkle: 1,
            zoom: 3,
            backgroundGlow: 0.5,
            opacity: 1,
            mouseInteraction: true,
            mouseStrength: 0.5,
            mouseRadius: 1,
            mouseDampening: 0.15,
            dpr: 1,
        },
    },
    {
        kind: 'liquidEther',
        title: 'Liquid Ether',
        description: 'Interactive fluid color',
        defaults: {
            colors: ['#5227ff', '#ff9ffc', '#b497cf'],
            backgroundColor: '#0d1012',
            mouseForce: 20,
            cursorSize: 100,
            isViscous: false,
            viscous: 30,
            iterationsViscous: 32,
            iterationsPoisson: 32,
            dt: 0.014,
            BFECC: true,
            resolution: 0.5,
            isBounce: false,
            autoDemo: true,
            autoSpeed: 0.5,
            autoIntensity: 2.2,
            takeoverDuration: 0.25,
            autoResumeDelay: 1000,
            autoRampDuration: 0.6,
        },
    },
    {
        kind: 'prism',
        title: 'Prism',
        description: 'Rotating refractive prism',
        defaults: {
            height: 3.5,
            baseWidth: 5.5,
            animationType: 'rotate',
            glow: 1,
            offsetX: 0,
            offsetY: 0,
            noise: 0.5,
            transparent: true,
            scale: 3.6,
            hueShift: 0,
            colorFrequency: 1,
            hoverStrength: 2,
            inertia: 0.05,
            bloom: 1,
            timeScale: 0.5,
        },
        choices: { animationType: ['rotate', 'hover', '3drotate'] },
    },
    {
        kind: 'darkVeil',
        title: 'Dark Veil',
        description: 'Dark flowing shader',
        defaults: {
            hueShift: 0,
            noiseIntensity: 0,
            scanlineIntensity: 0,
            speed: 0.5,
            scanlineFrequency: 0,
            warpAmount: 0,
            resolutionScale: 1,
        },
    },
    {
        kind: 'lightPillar',
        title: 'Light Pillar',
        description: 'Volumetric pillar of light',
        defaults: {
            topColor: '#5227ff',
            bottomColor: '#ff9ffc',
            intensity: 1,
            rotationSpeed: 0.3,
            interactive: false,
            glowAmount: 0.005,
            pillarWidth: 3,
            pillarHeight: 0.4,
            noiseIntensity: 0.5,
            pillarRotation: 0,
            quality: 'high',
        },
        choices: { quality: ['low', 'medium', 'high'] },
    },
];
