import type { EffectDefinition } from './react-bits-catalog';

export const secondEffects: EffectDefinition[] = [
    {
        kind: 'silk',
        title: 'Silk',
        description: 'Soft flowing fabric',
        defaults: {
            color: '#7b7481',
            speed: 5,
            scale: 1,
            noiseIntensity: 1.5,
            rotation: 0,
        },
    },
    {
        kind: 'softAurora',
        title: 'Soft Aurora',
        description: 'Layered aurora bands',
        defaults: {
            color1: '#f7f7f7',
            color2: '#e100ff',
            speed: 0.6,
            scale: 1.5,
            brightness: 1,
            noiseFrequency: 2.5,
            noiseAmplitude: 1,
            bandHeight: 0.5,
            bandSpread: 1,
            octaveDecay: 0.1,
            layerOffset: 0,
            colorSpeed: 1,
            enableMouseInteraction: true,
            mouseInfluence: 0.25,
        },
    },
    {
        kind: 'aurora',
        title: 'Aurora',
        description: 'Luminous horizon',
        defaults: {
            colorStops: ['#5227ff', '#7cff67', '#5227ff'],
            amplitude: 1,
            blend: 0.5,
        },
    },
    {
        kind: 'plasma',
        title: 'Plasma',
        description: 'Fluid plasma field',
        defaults: {
            color: '#ffffff',
            speed: 1,
            direction: 'forward',
            scale: 1,
            opacity: 1,
            mouseInteractive: true,
            renderScale: 0.55,
            maxDpr: 1.25,
            targetFps: 60,
            iterations: 60,
        },
        choices: { direction: ['forward', 'reverse', 'pingpong'] },
    },
    {
        kind: 'grainient',
        title: 'Grainient',
        description: 'Textured gradient motion',
        defaults: {
            color1: '#ff9ffc',
            color2: '#5227ff',
            color3: '#b497cf',
            timeSpeed: 0.25,
            colorBalance: 0,
            warpStrength: 1,
            warpFrequency: 5,
            warpSpeed: 2,
            warpAmplitude: 50,
            blendAngle: 0,
            blendSoftness: 0.05,
            rotationAmount: 500,
            noiseScale: 2,
            grainAmount: 0.1,
            grainScale: 2,
            grainAnimated: false,
            contrast: 1.5,
            gamma: 1,
            saturation: 1,
            centerX: 0,
            centerY: 0,
            zoom: 0.9,
        },
    },
    {
        kind: 'prismaticBurst',
        title: 'Prismatic Burst',
        description: 'Radiating colored rays',
        defaults: {
            colors: ['#ff9ffc', '#5227ff', '#b497cf'],
            intensity: 2,
            speed: 0.5,
            animationType: 'rotate3d',
            distort: 0,
            offsetX: 0,
            offsetY: 0,
            hoverDampness: 0,
            rayCount: 12,
        },
        choices: { animationType: ['rotate3d', 'rotate', 'hover'] },
    },
    {
        kind: 'hyperspeed',
        title: 'Hyperspeed',
        description: 'High speed light road',
        defaults: {
            preset: 'one',
            speedUp: 2,
            roadWidth: 10,
            lanesPerRoad: 3,
            fov: 90,
            lightPairsPerRoadWay: 40,
            totalSideLightSticks: 20,
            leftCarsColor: '#d856bf',
            rightCarsColor: '#03b3c3',
            backgroundColor: '#000000',
        },
        choices: { preset: ['one', 'two', 'three', 'four', 'five', 'six'] },
    },
    {
        kind: 'iridescence',
        title: 'Iridescence',
        description: 'Pearlescent color field',
        defaults: {
            color: '#ffffff',
            speed: 1,
            amplitude: 0.1,
            mouseReact: true,
        },
    },
];
